swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /movimiento/:
    get:
      tags:
      - movimiento
      description: get Movimiento
      operationId: MovimientoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Movimiento'
        "403":
          description: ""
    post:
      tags:
      - movimiento
      description: create Movimiento
      operationId: MovimientoController.Post
      parameters:
      - in: body
        name: body
        description: body for Movimiento content
        required: true
        schema:
          $ref: '#/definitions/models.Movimiento'
      responses:
        "201":
          description: '{int} models.Movimiento'
        "403":
          description: body is empty
  /movimiento/{id}:
    get:
      tags:
      - movimiento
      description: get Movimiento by id
      operationId: MovimientoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Movimiento'
        "403":
          description: :id is empty
    put:
      tags:
      - movimiento
      description: update the Movimiento
      operationId: MovimientoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Movimiento content
        required: true
        schema:
          $ref: '#/definitions/models.Movimiento'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Movimiento'
        "403":
          description: :id is not int
    delete:
      tags:
      - movimiento
      description: delete the Movimiento
      operationId: MovimientoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /transaccion/:
    get:
      tags:
      - transaccion
      description: get Transaccion
      operationId: TransaccionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Transaccion'
        "403":
          description: ""
    post:
      tags:
      - transaccion
      description: create Transaccion
      operationId: TransaccionController.Post
      parameters:
      - in: body
        name: body
        description: body for Transaccion content
        required: true
        schema:
          $ref: '#/definitions/models.Transaccion'
      responses:
        "201":
          description: '{int} models.Transaccion'
        "403":
          description: body is empty
  /transaccion/{id}:
    get:
      tags:
      - transaccion
      description: get Transaccion by id
      operationId: TransaccionController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Transaccion'
        "403":
          description: :id is empty
    put:
      tags:
      - transaccion
      description: update the Transaccion
      operationId: TransaccionController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Transaccion content
        required: true
        schema:
          $ref: '#/definitions/models.Transaccion'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Transaccion'
        "403":
          description: :id is not int
    delete:
      tags:
      - transaccion
      description: delete the Transaccion
      operationId: TransaccionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Movimiento:
    title: Movimiento
    type: object
    properties:
      Activo:
        type: boolean
      CuentaId:
        type: string
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      NombreCuenta:
        type: string
      TerceroId:
        type: integer
        format: int64
      TipoMovimientoId:
        type: integer
        format: int64
      TransaccionId:
        $ref: '#/definitions/models.Transaccion'
      Valor:
        type: number
        format: double
  models.Transaccion:
    title: Transaccion
    type: object
    properties:
      Activo:
        type: boolean
      ConsecutivoId:
        type: integer
        format: int64
      Descripcion:
        type: string
      EstadoId:
        type: integer
        format: int64
      Etiquetas:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      FechaTransaccion:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
tags:
- name: transaccion
  description: |
    TransaccionController operations for Transaccion
- name: movimiento
  description: |
    MovimientoController operations for Movimiento
